name: Lint, Build, Test & Publish

on:
  push:	
    branches:	
      - dev
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: Lint
      uses: luke142367/Docker-Lint-Action@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET: Dockerfile
    - name: Build
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: squizduos/code-server-dev
          tags: dev,${{ github.ref }}
    - name: Execute SSH commmands on remote server
      uses: JimCronqvist/action-ssh@master
      env:
        NAME: "Root"
      with:
        hosts: 'root@{{ secrets.SERVER }}'
        privateKey: ${{ secrets.PRIVATE_KEY }}
        debug: false
        command: |
          docker pull squizduos/code-server-dev:dev
          docker-compose restart code-server
    - name: send custom message while finished
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: html
        message: |
          <b>Gitlab Actions notification from</b> ${{ secrets.TELEGRAM_NAME }} ${{ secrets.TELEGRAM_USERNAME }}
          Workflow <code>${{ github.workflow }}</code> for repo <code>{{ repo }}</code>
          Commit SHA <code>{{ commit.sha }}</code> with ref <code>{{ commit.ref }}</code>
